# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rubocop', '~> 0.71.0'

gem 'sinatra', '~> 2.0'

gem 'rerun', '~> 0.13.0'

gem 'puma', '~> 3.12'

gem 'capybara'
gem 'rspec', '~> 3.8'

gem 'simplecov', '~> 0.16.1'

gem 'erb_lint', '~> 0.0.28'
